//
// Created by ee211905 on 15/06/22.
//
#include <jni.h>
#ifndef HELLOWORLDGRPC_HELLOJNI_H
#define HELLOWORLDGRPC_HELLOJNI_H
#ifdef __cplusplus
extern "C" {
#endif
void sayHello ();
#ifdef __cplusplus
}
#endif
#endif //HELLOWORLDGRPC_HELLOJNI_H



/* sample JNI of HelloJNI.h file
 * DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_sayHello(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

// declaration as JNIEXPORT void JNICALL Java_HelloJNI_sayHello(JNIEnv *, jobject);
// (or) JNIEXPORT void JNICALL Java_Hello_sayHi (JNIEnv *, jobject, jstring, jint);


/* For HelloJNI.c
 *
 * #include <stdio.h>
 * #include "HelloJNI.h"   // Generated

// Implementation of the native method sayHello()
JNIEXPORT void JNICALL Java_HelloJNI_sayHello(JNIEnv *env, jobject thisObj) {
   printf("Hello World!\n");
   return;
(or)
 JNIEXPORT void JNICALL Java_Hello_sayHi(JNIEnv *env, jobject obj, jstring who, jint times) {
	jint i;
	jboolean iscopy;
	const char *name;
	name = (*env)->GetStringUTFChars(env, who, &iscopy);
	for (i = 0; i < times; i++) {
		printf("Hello %s\n", name);
	}
}
 ----> o/p as Hello Student * (ntimes)
}*/